image: maven:latest

stages:
  - build
  - report
  - publish

variables:
  MAVEN_CLI_OPTS: "--batch-mode -Pmpijava"

cache:
  paths:
    - target/

project_compile:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package
    
javadoc:
  stage: report
  script: 
    - mvn $MAVEN_CLI_OPTS site

publish:
  stage: report
  script:
    - mvn $MAVEN_CLI_OPTS site
    - cd target
    - git clone --single-branch --branch gh-pages https://github.com/handist/mpi-junit.git
    - rm -rf mpi-junit/master-latest
    - mkdir mpi-junit/master-latest
    - cp -r site/* mpi-junit/master-latest/
    - cd mpi-junit
    - git add master-latest
    - git commit -m "${CI_COMMIT_MESSAGE}"
    - git remote set-url origin https://${GITHUB_USER}:${GITHUB_OAUTH}@github.com/handist/mpi-junit.git
    - git push origin gh-pages
  only: 
    - master
